
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  namespace: nondynatrace
  labels:
    app: fluentd
    component: fluentd-conf
data:
  CLUSTER_ID: "CLUSTER_ID_TO_REPLACE"
  AG_INGEST_URL: "https://fluentd-activegate:9999/e/ENVIRONMENT_ID_TO_REPLACE/api/v2/logs/ingest"
  fluent.conf: |-
    # Ingest logs from nodes
    <match fluent.**>
      @type null
    </match>

    <source>
      @type tail
      path /var/log/containers/*nginx*.log
      pos_file /var/log/fluentd.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag nginx
      <parse>
        @type nginx
        key_name log
        reserve_data yes
        expression  /^(?<ip>\S+)\s+\[(?<time_local>[^\]]*)\]\s+(?<method>\S+)\s+(?<request>\S+)\s+(?<httpversion>\S*)\s+(?<status>\S*)\s+(?<bytes_sent>\S*)\s+(?<responsetime>\S*)\s+(?<proxy>\S*)\s+(?<upstream_responsetime>\S*)\s+(?<resourcename>\S*)\s+(?<upstream_status>\S*)\s+(?<ingress_name>\S*)\s+(?<resource_type>\S*)\s+(?<resource_namespace>\S*)\s+(?<service>\w*)/

      </parse>
      read_from_head true
      keep_time_key true
    </source>


    <match nginx>
        @type  stdout
    </match>
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: nondynatrace
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        app: fluentd-pipeline
    spec:
      serviceAccountName: dynatrace-monitoring
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      initContainers:
      - name: fluentd-permission-fix
        image: busybox
        command: [ "sh","-c","touch /var/log/fluentd.pos; chmod -R 777 /var/log/fluentd.pos; " ]
        volumeMounts:
          - name: var-log
            mountPath: /var/log/
      containers:
      - name: fluentd
        image: hrexed/fluentd_dynatrace_prometheus:0.1
        ports:
          - containerPort: 9914
            name: fluentdprom
            protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
            ephemeral-storage: 10Gi
          requests:
            cpu: 100m
            memory: 200Mi
            ephemeral-storage: 10Gi
        env:
          - name: FLUENT_UID
            value: "0"
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: fluentd-conf
                key: CLUSTER_ID
          - name: AG_INGEST_URL
            valueFrom:
              configMapKeyRef:
                name: fluentd-conf
                key: AG_INGEST_URL
          - name: LOG_INGEST_TOKEN
            valueFrom:
              secretKeyRef:
                name: tokens
                key: log-ingest
        volumeMounts:
          - name: var-log
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: var-log-pos
            mountPath: /var/log/fluentd.pos
          - mountPath: /fluentd/etc/fluent.conf
            name: data
            subPath: fluent.conf
            readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: var-log
          hostPath:
            path: /var/log/
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: var-log-pos
          hostPath:
            path: /var/log/fluentd.pos
            type: FileOrCreate
        - name: data
          configMap:
            name: fluentd-conf


