apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
  namespace: nondynatrace
  labels:
    app: fluentd
    component: fluentd-conf
data:
  CLUSTER_ID: "CLUSTER_ID_TO_REPLACE"
  AG_INGEST_URL: "https://fluentd-activegate:9999/e/ENVIRONMENT_ID_TO_REPLACE/api/v2/logs/ingest"
  fluent.conf: |-
    # Ingest logs from nodes
     <match fluent.**>
      @type null
     </match>

     <source>
       @type tail
       path /var/log/containers/*nginx*.log
       pos_file /var/log/fluentd.pos
       time_format %Y-%m-%dT%H:%M:%S.%NZ
       read_from_head true
       tag nginx
       keep_time_key true
     <parse>
       @type nginx
       reserve_data yes
       expression  /^(?<ip>\S+)\s+\[(?<time_local>[^\]]*)\]\s+(?<method>\S+)\s+(?<request>\S+)\s+(?<httpversion>\S*)\s+(?<status>\S*)\s+(?<bytes_sent>\S*)\s+(?<responsetime>\S*)\s+(?<proxy>\S*)\s+(?<upstream_responsetime>\S*)\s+(?<resourcename>\S*)\s+(?<upstream_status>\S*)\s+(?<ingress_name>\S*)\s+(?<resource_type>\S*)\s+(?<resource_namespace>\S*)\s+(?<service>\w*)/
       types ip:string,time_local:string,method:string,request:string,httpversion:string,status:string,bytes_sent:integer,responsetime:float,proxy:string,upstream_responsetime:integer,resourcename:string,upstream_status:string,ingress_name:string,resource_type:string,resource_namespace:string,service:string
       time_key time_local
       time_format %d/%b/%Y:%H:%M:%S %z
     </parse>

     </source>
     <source>
       @type prometheus
       bind 0.0.0.0
       port 9914
       metrics_path /metrics
     </source>

     <filter nginx>
       @type kubernetes_metadata
     </filter>

     <filter  nginx>
      @type prometheus
       <labels>
         method ${method}
         request ${request}
         status ${status}
         namespace ${resource_namespace}
         service ${service}
         ressourcename ${resourcename}
       </labels>
       <metric>
         name hotday_response_time
         type gauge
         desc response time
         key responsetime
       </metric>
       <metric>
         name hotday_byte_sent
         type gauge
         desc byte sent
         key bytes_sent
       </metric>
       <metric>
         name hotday_requests
         type counter
         desc The total number of request
       </metric>
       <metric>
         name hotday_status
         type counter
         desc status code
         key status
       </metric>
     </filter>

     <filter nginx>
        @type grep
          <exclude>
          key service
          pattern /^$/
          # or, to exclude all messages that are empty or include only white-space:
          </exclude>
     </filter>

     <filter nginx>
       @type record_transformer
       enable_ruby true
       <record>
         status ${ record.dig(:log, :severity) || record.dig(:log, :level) || (record["log"] =~ /\W?\berror\b\W?/i ? "ERROR" : (record["log"] =~ /\W?\bwarn\b\W?/i ? "WARN" : (record["log"] =~ /\W?\bdebug\b\W?/i ? "DEBUG" : (record["log"] =~ /\W?\binfo\b\W?/i ? "INFO" : "NONE")))) }
         content ${record["method"]} ${record["request"]} ${record["status"]} ${record["service"]} ${record["bytes_sent"]} ${record["responsetime"]} ${record["service"]}
         dt.kubernetes.node.system_uuid ${File.read("/sys/devices/virtual/dmi/id/product_uuid").strip}
         dt.kubernetes.cluster.id "#{ENV['CLUSTER_ID']}"
         k8s.namespace.name ${record["resource_namespace"]}
         k8s.service.name ${record["service"]}
       </record>
       remove_keys  nginx
     </filter>

     <match nginx>
       @type              dynatrace
       active_gate_url "#{ENV['AG_INGEST_URL']}"
       api_token "#{ENV['LOG_INGEST_TOKEN']}"
       ssl_verify_none    true
     </match>
