apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd-exporter
  name: fluentd-prom-metrics
  annotations:
    metrics.dynatrace.com/port: "TO_DEFINE"
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: '/metrics'
spec:
  ports:
    - port: 9914
      name: fluentdprom
      targetPort: fluentdprom
      protocol: TCP
  selector:
    app: fluentd-pipeline