kind: Service
apiVersion: v1
metadata:
  name: hotday-kube-state
  annotations:
    metrics.dynatrace.com/port: "TO_DEFINE"
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: '/metrics'
spec:
  ports:
    - name: kube-port
      targetPort: kube-port
      protocol: TCP
      port: 8080
  selector:
          app.kubernetes.io/name: kube-state-metrics
  clusterIP: None
